### ISSUE TITLE
Character limit in "Name" field is too low

### ISSUE THREAD

**Issue by VertebreakHER** [craigmc08/drg-editor#11]
The limit on the "Name" field is low enough that adding certain imports is impossible through the editor. The specific example in this case being "/Game/WeaponsNTools/Grenades/HighExplosive/ID_Grenades_HighExplosive" which is needed to add HE Grenades as a throwable for other classes.

**Comment by craigmc08** [comment]
This should be fixed in [v0.1.1](https://github.com/craigmc08/drg-editor/releases/tag/v0.1). Could you test it out?

**Comment by VertebreakHER** [comment]
The new version seems to work just fine and has completely resolved the problem. Thank you so much!
